### PR TITLE
Add options for authenticate, protected mode, communitated cluster using hostname, clean/keep data file before start

### PR DESCRIPTION
**Pull request by QuyenTran93**

### CODE REVIEW

**Comment by Grokzen** [comment]
@QuyenTran93 Why was this closed?

**Comment by QuyenTran93** [comment]
> @QuyenTran93 Why was this closed?

Sorry bro, I need to check these options for sentinel.

**Comment by QuyenTran93** [comment]
@Grokzen I was add environment RESET_DATA for handle remove/keep redis-data file before start redis.
I've tested this on my machine and published new tag to `https://hub.docker.com/r/duyquyen/redis-cluster`

**Comment by dtomasi** [comment]
@Grokzen @QuyenTran93 is there any progress? Looking forward to see this, as I want to use it in some tests. Currently this blocks me, as redis starts in protected mode in the test environment and its not that easy to invoke redis cli commands there.

Thanks a lot

**Comment by QuyenTran93** [comment]
> @Grokzen @QuyenTran93 is there any progress? Looking forward to see this, as I want to use it in some tests. Currently this blocks me, as redis starts in protected mode in the test environment and its not that easy to invoke redis cli commands there.
> 
> Thanks a lot

@dtomasi You can using my custom image - [the temporary image](https://hub.docker.com/r/duyquyen/redis-cluster/tags) until grokzen/redis-cluster support protected mode

**Pull request closed without merging**
