### PR TITLE
Include persistence instruction in README.md

### PR DESCRIPTION
**Pull request by yang-wei**

### CODE REVIEW

**Comment by yang-wei** [comment]
Turned out it doesn't work this way. 

Would you like to support this ?
I can make a PR

**Comment by Grokzen** [comment]
What do you want to achive @yang-wei ? This container is not really built for keeping data persistent between start/stops of the same container as there has been issues in the past with startup a cluster from 0 requires more steps to restart the cluster from existing data. I personally dont have a need for it and in general the container was not designed for this, but if you want to take a stab at it and see if it is possible to persist the data between runs, then go ahead and submit a PR. I will consider any submitted PR.

**Comment by yang-wei** [comment]
I use redis as persistent layer so it will be nice if my data can be kept locally for some time.

**Comment by Grokzen** [comment]
@yang-wei If you can sort out the instructions and make it work between restarts then go ahead and try and submit a PR and i will have a look at it. But do note that this repo is more of a demo/test/ci image and not really built for persistence between different runs. But if you can make it work with all different combinations and solutions and the dynamic nature of the different redis versions and work with sentinel, cluster, standalone and a dynamically size of them then please do submit a PR for it and we can get it in.

**Comment by Grokzen** [comment]
I will close this PR as it would never be merged, please open up a new PR for the additional work we talked about in here.

**Pull request closed without merging**
