### PR TITLE
Added support for password

### PR DESCRIPTION
**Pull request by nishantgeorge**
A password can be specified by passing a `REQUIREPASS` environment variable.
This password is set for both the `requirepass` and `masterauth` configuration parameters for all servers in the cluster.

### CODE REVIEW

**Comment by Grokzen** [comment]
@nishantgeorge If i use this code, but do not set any value for the password fields and they are provisioned inside the redisconf for the server, will the server accept and still run if it only contains `requirepass` & `masterauth` with no value to it and dont server the redis instance with a password?

**Comment by nishantgeorge** [comment]
Well, up till Redis 5, setting an empty string as a password was the same as not setting a password, but this is not true for Redis 6 anymore. Redis 6 sets a zero-length string as the password. See [this](https://github.com/antirez/redis/issues/3557#issuecomment-533009285) comment.

So I guess this implementation is not a good idea for the future and we can close this PR.

**Comment by Grokzen** [comment]
@nishantgeorge Do you want to update this PR to work for both 5.0 and below and 6.0 and above solutions at the same time or do you want to close this one and let someone else attempt to implement this in the future in a new way?

**Comment by nishantgeorge** [comment]
I think it's best to close this and implement it separately.

**Pull request closed without merging**
