### PR TITLE
Dynamically generate supervisor conf file based on env variable (allows omitting standalones)

### PR DESCRIPTION
**Pull request by Druotic**
@Grokzen We chatted about this briefly some time ago, but I finally got around to implementing it (and some of the templating changes you made since then made this easier). For my particular use case, the only issue with using this project was that I didn't want the two standalone redis instances running in the container. This change allows a runtime environment variable `CLUSTER_ONLY` to be specified. If it is "true", only the 3 masters and 3 slaves will be started.

An added bonus is that because this is a runtime configuration option, the same image can be used for either configuration.

note: backwards compatibility is maintained if the environment variable is omitted.

### CODE REVIEW

**Comment by Druotic** [comment]
@Grokzen Any thoughts on this? I'm willing to make any necessary changes to get this merged.

**Comment by Druotic** [comment]
Is there anything I can do to expedite getting this merged? I would love to use this image and avoid maintaining a fork if at all possible.

**Comment by Grokzen** [comment]
@Druotic I am back from a long vacation now. I will start to process all my github backlog during the weekend and over the next week.

**Comment by Druotic** [comment]
@Grokzen Just checking in - any progress on reviewing this?

**Comment by austinkelleher** [comment]
@Grokzen I really could use this change too. Is there any way you could get around to reviewing it and merging? Thanks in advance.

**Comment by austinkelleher** [comment]
@Grokzen Also great work on this project. It's been super useful!

**Comment by Druotic** [comment]
Hello again - checking back to see if everything looks good. Any changes you'd like to see?

**Pull request merged**
