### PR TITLE
Make number of nodes configurable

### PR DESCRIPTION
**Pull request by viniciusd**
This pull request solves #73 

I made my best so it could keep the project's coding style.

Any thoughts are welcome

### CODE REVIEW

**Comment by Grokzen** [comment]
@viniciusd There is 2 main issues i see with having this dynamic regarding ports. The default case have a fixed set of ports open from 7000-7007. But when this is dynamic then this will not work with how the code is right now as borth PORTS inside the Dockerfile and the port defenition in the compose file still has this set of ports. If this is not solved then a redis-cluster client is not capable to connect to all nodes in the cluster.

**Comment by Grokzen** [comment]
Another thing you need to do is to document this feature in the README.md file similar to how this has been done https://github.com/Grokzen/docker-redis-cluster#include-standalone-redis-instances and it should describe the environment variable flags that you need to  export on your system in order to correctly set the nodes and environment.

**Comment by Grokzen** [comment]
One simple solution that i could like/allow would maybe be to just hard code opening the ports 7000-7100 and just add to the README file that you can only have a max of 100 nodes (would be crazy if anyone used that many) and if you need more for any reaason you will have to fork this and alter the compose file yourself manually to suit your specific needs.

**Comment by viniciusd** [comment]
With regards to the documentation, I was waiting for your initial input in order to make sure I could place more time into this.

**Comment by viniciusd** [comment]
About the docker-compose, though, I agree with your workaround leaving a decent number allowed.
I mean, I personally think the docker-compose at this repository is mostly an example.
Alike the image itself, which is available at dockerhub for a wider public, e.g., CI services.

**Comment by Grokzen** [comment]
Yes and no. The main use-case when you run for CI and uses the image from dockerhub you are correct. But the main use if you clone this repo from here is to run `make build` & `make up` that in turn uses the docker-compose files so sorting the port case should be fixed atleast some. But i am totally fine by hardcoding say port 7000-7050 in the compose file and just add a line in the README file when you describe how to configure this feature through the envrionment variables that the result of the multiplication of masters + replicas + shards can't be over 50, otherwise you have to manually override it to support more nodes if you so need it. It don't have to be perfect or dynamic in the compose file, but it should at least be supported that you can test to double the number of shards, or slaves that will still produce less redis server nodes then 50.

**Comment by viniciusd** [comment]
Sorry for the long delay here. I started this PR while I was on holidays.

Updated both docker-compose and README.

**Comment by Grokzen** [comment]
@viniciusd Looks very good now. I will merge this this weekend and rebuild all images and push up new tags of all releases, it takes some time to build :)

**Comment by viniciusd** [comment]
Awesome! Let me know whether I can be of any extra assistance

Congrats for the awesome work putting this all together!

**Comment by Grokzen** [comment]
@viniciusd Thank you :) and many thanks to you as well for providing this huge addition to the docker image. New image tags should be uploaded today or tomorrow to dockerhub that includes these changes. Dont know how bad the rebuild timer will be.

**Pull request merged**
